DROP TABLE USER_SETTINGS;
DROP TABLE SERVER_SETTINGS;

CREATE TABLE IF NOT EXISTS SERVER_SETTINGS (
    guild_id    VARCHAR PRIMARY KEY,
    channel_id  VARCHAR
);

CREATE TABLE IF NOT EXISTS USER_SETTINGS (
    id          INT PRIMARY KEY,
    user_id     VARCHAR,
    cog_name    VARCHAR,
    guild_id    VARCHAR REFERENCES SERVER_SETTINGS,
);