DROP TABLE IF EXISTS USER_SETTINGS;
DROP TABLE IF EXISTS SERVER_SETTINGS;
DROP TABLE IF EXISTS USER_COG_NOTIFS;

CREATE TABLE IF NOT EXISTS SERVER_SETTINGS (
    guild_id    VARCHAR PRIMARY KEY,
    channel_id  VARCHAR
);

CREATE TABLE IF NOT EXISTS USER_SETTINGS (
    user_id     VARCHAR PRIMARY KEY,
    guild_id    VARCHAR REFERENCES SERVER_SETTINGS
);

CREATE TABLE IF NOT EXISTS USER_COG_NOTIFS (
    id          INT PRIMARY KEY,
    user_id     VARCHAR,
    cog_name    VARCHAR,
    UNIQUE (user_id, cog_name)
);